baseurl: /seoul
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: seoul
github_org: maptime
maptime:
  chapter: MaptimeSeoul
  #twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
